#define UP 0
#define DOWN 1
#define RIGHT 2
#define LEFT 3
#define FIRE_LEFT 4
#define FIRE_RIGHT 5
#define TILE_SIZE 16
#define SCREEN_HEIGHT (30*TILE_SIZE)
#define SCREEN_WIDTH (46*TILE_SIZE)
#define SKY 0
#define BRICK 1